[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.4.0",
    "numpy==2.2.0",
    "scipy>=1.16.0",
    "xarray>=2025.7.1",
    "xmitgcm>=0.5.2",
]
